spring.application.name=Challenge_Sprint_2
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.data.mongodb.uri=
spring.data.mongodb.database=Inovacao_Gab
spring.ai.google.genai.chat.options.model=gemini-3.6-flash