spring.application.name=Challenge_Sprint_2
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.data.mongodb.uri=mongodb+srv://oluafv:NEBTMceL5jc3sQlF@cluster0.l5eecm8.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=Inovacao_Gab
spring.ai.google.genai.chat.options.model=gemini-3.6-flash